language: objective-c
osx_image: xcode7.3

script:
- set -o pipefail && xcodebuild test -project ReadabilityKit.xcodeproj -scheme ReadabilityKitTests -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' | xcpretty