language: objective-c
osx_image: xcode7.3

podfile: Example/Podfile

before_install:
# - gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/ReadabilityKit.xcworkspace -scheme ReadabilityKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' | xcpretty
- pod lib lint --allow-warnings